"""empty message

Revision ID: bd0e444a92fb
Revises: 11c505d45bea
Create Date: 2022-10-23 18:21:42.964299

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bd0e444a92fb'
down_revision = '11c505d45bea'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('answers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('modified_at', sa.DateTime(), nullable=True))

    with op.batch_alter_table('questions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('modified_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('questions', schema=None) as batch_op:
        batch_op.drop_column('modified_at')

    with op.batch_alter_table('answers', schema=None) as batch_op:
        batch_op.drop_column('modified_at')

    # ### end Alembic commands ###
